services:
  api-tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    volumes:
      - ./api:/app
    working_dir: /app
    command: sh -lc "composer install && ./vendor/bin/phpunit --colors=always"
